<h2> Sesi 1 - Challenge: coba create gabungan antara list, string, dan integer yang nanti dicompare dengan menggunakan variable </h2>

In [ ]:
list_1 = ['a', 2, 'c', 3, 'de']
str_1 = 'I am me'
int_1 = 99

In [ ]:
merge_1 = [list_1, str_1, int_1]
print(merge_1)

In [ ]:
int_2 = 100
print(merge_1[2] == int_2)

str_list_1 = 'a2c3de'
print(merge_1[0] == str_list_1)

<h2> Sesi 2 - Challenge</h2>

In [ ]:
nama_panjang = input('nama panjang: ')
nama_pendek = input('nama pendek: ')
umur = input('umur: ')

list_string_nama_panjang = nama_panjang.split()
jumlah_kata = len(list_string_nama_panjang)

if jumlah_kata==3:
    print(nama_panjang)
elif jumlah_kata!=3:
    if int(umur) % 2 == 0:
        print(nama_panjang)
    else:
        print(nama_pendek)

In [ ]:
i = 0

clean_nama_panjang = nama_panjang.replace(' ','')

for n in clean_nama_panjang:
    i += 1
    print(i)

In [ ]:
nama = nama_pendek
list_1 = [1,2,3,4]
list_2 = [1,2,3,5]

if list_1 == list_2:
    print(list_1)
else:
    for i in list_1:
        print(nama)

<h2> Sesi 3 - Challenge </h2>

<p> kita membutuhkan fungsi untuk menghitung perkalian dari item2 di list A, kemudian hasil dari perkalian tersebut dikalikan ke setiap item di list B
contoh:
list_a = [1,2,3,4]
list_b = [4,5,6,7]
maka hasil dari fungsi: [96,120,144,168] </p>

In [ ]:
list_a = [1,2,3,4]
list_b = [4,5,6,7]

def func_case1(listA, listB):
    result = 1
    
    for x in listA:
        result = result * x;
    
    for x in range(0,len(listB),1):
        listB[x] = result * listB[x]
        
    return listB;

print(func_case1(list_a,list_b))

kita membuat 2 fungsi, dimana fungsi pertama adalah untuk mengecek input itu adalah suatu angka bukan huruf dan apakah angka itu dapat dibagi oleh suatu angka, hasil dari fungsi tersebut adalah true atau false
fungsi yg kedua adalah apabila hasil dari fungsi pertama itu adalah true, maka kita akan mempangkatkan angka tersebut dengan pangkat yang kita inginkan, dan apabila false maka keluar kata2: "input bukan angka" atau "input tidak bisa dibagi 2"
contoh:
input: 10
pangkat: 3
maka hasil

In [ ]:
base = input('input: ')
power = int(input('pangkat: '))

def func_case2_isDivisibleByTwo(num):
    
    if base.isnumeric():
        if int(num)%2 == 0:
            return True
        else:
            print('input tidak bisa dibagi 2');
            return False
    else:
        print('input bukan angka');
        return False
    
def func_case2_calculatePower(baseNum, powerNum):
    
    check = func_case2_isDivisibleByTwo(baseNum)
    
    if check:
        return int(baseNum)**powerNum
    else:
        return ''

print(func_case2_calculatePower(base, power))

<h2> Sesi 4 - Challenge </h2>

In [1]:
import numpy as np

Case:<br></br>Create Create numpy array from your inputted full name in the form of numbers based on order in alphabets. You can use this translater to change from alphabet to number:
```py
letter_to_word = {'a': 1, 'c': 3, 'b': 2, 'e': 5, 'd': 4, 'g': 7, 'f': 6, 'i': 9, 'h': 8, 'k': 11, 'j': 10, 'm': 13, 'l': 12, 'o': 15, 'n': 14, 'q': 17, 'p': 16, 's': 19, 'r': 18, 'u': 21, 't': 20, 'w': 23, 'v': 22, 'y': 25, 'x': 24, 'z': 26}
```
Also add repetition on the number based on your inputted number.
Example:
inputted full name = 'Jenny'<br>
repeated = 4 times<br>
result:<br>
```
[[10  5 14 14 25]
 [10  5 14 14 25]
 [10  5 14 14 25]
 [10  5 14 14 25]]
```

In [2]:
letter_to_word = {'a': 1, 'c': 3, 'b': 2, 'e': 5, 'd': 4, 'g': 7, 'f': 6, 'i': 9, 'h': 8, 'k': 11, 'j': 10, 'm': 13, 'l': 12, 'o': 15, 'n': 14, 'q': 17, 'p': 16, 's': 19, 'r': 18, 'u': 21, 't': 20, 'w': 23, 'v': 22, 'y': 25, 'x': 24, 'z': 26}

name = str(input('name:'))
repeated = int(input('repeated:'))

# Step 1 - create name array

arr_name = np.empty(0, dtype=int)

for i in name:
    arr_name = np.append(arr_name, np.array([letter_to_word[i]]))

# Step 2 - repeat array

arr_result = np.full((repeated,len(arr_name)), arr_name, dtype=int)

print(arr_result)

name:resha
repeated:5
[[18  5 19  8  1]
 [18  5 19  8  1]
 [18  5 19  8  1]
 [18  5 19  8  1]
 [18  5 19  8  1]]
